// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown

/* eslint-disable */

export * from "./sedachain/wasm_storage/v1/wasm_storage.js";
export * from "./sedachain/wasm_storage/v1/events.js";
export * from "./sedachain/wasm_storage/v1/genesis.js";
export * from "./sedachain/wasm_storage/v1/query.js";
export * from "./sedachain/wasm_storage/v1/tx.js";
