// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown

/* eslint-disable */

export * as randomness from "./index.sedachain.randomness.js";
export * as staking from "./index.sedachain.staking.js";
export * as vesting from "./index.sedachain.vesting.js";
export * as wasm_storage from "./index.sedachain.wasm_storage.js";
