// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown

/* eslint-disable */

export * from "./sedachain/vesting/v1/tx.js";
export * from "./sedachain/vesting/v1/vesting.js";
