// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown

/* eslint-disable */

export * from "./google/protobuf/descriptor.js";
export * from "./google/protobuf/any.js";
export * from "./google/protobuf/duration.js";
export * from "./google/protobuf/timestamp.js";
