// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown

/* eslint-disable */

export * from "./tendermint/types/validator.js";
export * from "./tendermint/types/types.js";
export * from "./tendermint/types/params.js";
